version = 0.1
[default.deploy.parameters]
stack_name = "sls-python-app-tags"
resolve_s3 = true
s3_prefix = "sls-python-app-tags"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"Dev\""
image_repositories = []
